### ISSUE TITLE
Add export-all button to schedule

### ISSUE THREAD

**Issue by ritave** [efdevcon/devcon-website#150]
I'd like to see all of my talks on my calendar to resolve conflicts and to have integrated.

Adding it one by one is cumbersome. Having an export-all button that creates one .ics file, or multiple in .zip would be useful

**Comment by wslyvh** [comment]
Great suggestions. We'll definitely try to look into this before event starts.

**Comment by wslyvh** [comment]
Hi @ritave 

We just pushed an update that allows you to download your personal schedule to .ics or .csv format.
The later is more useful to e.g. import into Google Calendar

![image](https://user-images.githubusercontent.com/25974464/194719805-674679a3-0224-49b0-8f0d-3c1667160a49.png)

Hope that works!

**Comment by ritave** [comment]
Confirmed it works. Thank you very much!
