### ISSUE TITLE
Consider increasing session expiry

### ISSUE THREAD

**Issue by gnattishness** [efdevcon/devcon-website#160]
Hello, could you increase the default session expiry, or allow it to be configurably extended?

E.g. with a "keep me signed in" check box?

https://github.com/efdevcon/devcon-website/blob/f29bd2bc16ff122b68b40df0dbab8bfce491f45e/src/pages/api/account/token.ts#L30

**Comment by wslyvh** [comment]
Hi @gnattishness, thanks for your feedback. Extending session expiration is high on our priority list.
Will keep you updated!

**Comment by wslyvh** [comment]
Solved with #168 

Thank you @randylien 🙏
