### ISSUE TITLE
When going on the agenda schedule back filters are lost 

### ISSUE THREAD

**Issue by kristianpaul** [efdevcon/devcon-website#162]
On iOS/Safari when you are navigating  the schedule agenda and happen to have the “ATTENDING” enabled then (1) you select on of the events for more details and then (2) go back using the swipe left gesture  the aforementioned “ATTENDING” filter is gone and you hace to scroll up back agaib and enable it

**Comment by lassejaco** [comment]
b2f04f5a3d32c9c09ef70a6a819d02cbb71dfc7f fixes this

Thanks for the feedback, filter should persist between page navigation now
