### ISSUE TITLE
Filter "null"

### ISSUE THREAD

**Issue by ligi** [efdevcon/devcon-website#176]
Currently if a speaker description is not available we show "null"
but IMHO we should just not write anything here

![image](https://user-images.githubusercontent.com/111600/197257080-a2810b77-4e69-4df1-a68e-d3d58ff20ac1.png)

**Comment by wslyvh** [comment]
Fixed in https://github.com/efdevcon/devcon-website/commit/fe07b9b5eb49a685dff93fadd29c2d45938274db
