### ISSUE TITLE
devcon-archive: add length filter

### ISSUE THREAD

**Issue by ligi** [efdevcon/devcon-website#181]
I think it would be nice to be able to filter by length or talk type. Sometimes you only have little time and e.g. want to see all lightning talks to watch one of them.

**Comment by wslyvh** [comment]
Added a type filter. 

Filtering on duration would be a bit more tricky if you want to filter on lightning talks. Quick search resulted in lightning talks from +10mins to > 5 mins. 

I guess the combination of filtering by type + sort on duration would solve your issue?
